### ISSUE TITLE
External Script doesnt add a button in the ribbon

### ISSUE THREAD

**Issue by ghost** [chuongmep/CadPythonShell#12]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

When uploading an external script, it doesnt create a button in the ribbon, even if i restart autocad. In the revit version it does, so other people can reuse my scripts just by click in it.

### Release version

1.1.3

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Go to Python Shell Menu.
2. Click in configures CPS.
3. In External Scripts Add a .py script.
4. Give a Name and Ok.
5. It does nothing.

**Comment by chuongmep** [comment]
Hi @asessLuis . At the moment, I don't have any plan to implement that feature, I wish I have anough time to help but will consider when I have free time.

**Comment by ghost** [comment]
Hi Chuong, thanks for your response and all the effort, apreciate it! Understood and understandable!
