### ISSUE TITLE
Cannot import ifcopenshell

### ISSUE THREAD

**Issue by TZwielehner** [chuongmep/CadPythonShell#2]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

I tried to import the following module but it doesn't work. 
http://ifcopenshell.org/python
I used the win 32 bit 2.7 version.

### Release version

1.0.5

### Operating system

Windows 10

**Comment by Cyril-Pop** [comment]
Hello
ifcopenshell is not a pure python library, it contains Windows dll file (pyd files)
CadPythonShell is built on the Ironpython engine, and currently it does not support using PYDs built for CPython since they leverage implementation details of CPython.

**Comment by TZwielehner** [comment]
That's a pity. Is CPython on the roadmap? It is supported in RevitPythonShell...

**Comment by chuongmep** [comment]
@TZwielehner, i'm still experimenting with pythonnet to connect directly to the latest python libraries, i just do them in my spare time so there are no guarantees, so don't expect too much, if you have any pull request i will consider.

**Comment by chuongmep** [comment]
Version 1.0.9 will be support tartget ironpython 3.4
