### ISSUE TITLE
Doubled items in `snoop database`

### ISSUE THREAD

**Issue by mastrolube** [chuongmep/CadPythonShell#4]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

Hello! Very nice and useful tool! 

Just want to report that all the items are doubled as you can see at the bottom in the screenshot section.
Every element I've inspected has that doubled data, I've also checked and they are the same.

### Release version

1.0.7

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Open a drawing
2. Snoop Database
3. Inspect elements

### Screenshots

![immagine](https://user-images.githubusercontent.com/52335835/167918558-1faf9486-b207-4996-8c18-6ce236477f8c.png)
![immagine](https://user-images.githubusercontent.com/52335835/167918714-d99160a2-c77e-4e7d-8516-b5982925894d.png)

**Comment by chuongmep** [comment]
@mastrolube Many thanks reported, I will fix soon when i have free time.

**Comment by chuongmep** [comment]
@mastrolube fixed in version 1.0.8
